import { z } from 'zod';
export declare const AppointmentSchema: z.ZodObject<{
    appointmentID: z.ZodString;
    userID: z.ZodString;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    appointmentType: z.ZodDefault<z.ZodEnum<["general", "doctor", "business", "personal"]>>;
    startDateTime: z.ZodString;
    endDateTime: z.ZodString;
    allDayEvent: z.ZodDefault<z.ZodBoolean>;
    location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isVirtual: z.ZodDefault<z.ZodBoolean>;
    meetingLink: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    meetingPlatform: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>;
    reminderMinutesBefore: z.ZodDefault<z.ZodNumber>;
    isRecurring: z.ZodDefault<z.ZodBoolean>;
    recurrencePattern: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    calendarColor: z.ZodDefault<z.ZodString>;
    externalEventID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isDeleted: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    userID: string;
    isDeleted: boolean;
    createdAt: string;
    updatedAt: string;
    status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
    title: string;
    isRecurring: boolean;
    externalSyncStatus: "not_synced" | "synced" | "failed";
    appointmentID: string;
    appointmentType: "general" | "doctor" | "business" | "personal";
    startDateTime: string;
    endDateTime: string;
    allDayEvent: boolean;
    isVirtual: boolean;
    reminderMinutesBefore: number;
    calendarColor: string;
    description?: string | null | undefined;
    notes?: string | null | undefined;
    location?: string | null | undefined;
    meetingLink?: string | null | undefined;
    meetingPlatform?: string | null | undefined;
    recurrencePattern?: string | null | undefined;
    externalEventID?: string | null | undefined;
}, {
    userID: string;
    createdAt: string;
    updatedAt: string;
    title: string;
    appointmentID: string;
    startDateTime: string;
    endDateTime: string;
    isDeleted?: boolean | undefined;
    status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
    description?: string | null | undefined;
    isRecurring?: boolean | undefined;
    externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
    notes?: string | null | undefined;
    appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
    allDayEvent?: boolean | undefined;
    location?: string | null | undefined;
    isVirtual?: boolean | undefined;
    meetingLink?: string | null | undefined;
    meetingPlatform?: string | null | undefined;
    reminderMinutesBefore?: number | undefined;
    recurrencePattern?: string | null | undefined;
    calendarColor?: string | undefined;
    externalEventID?: string | null | undefined;
}>;
export type Appointment = z.infer<typeof AppointmentSchema>;
//# sourceMappingURL=appointments.schema.d.ts.map