import { z } from 'zod';
export declare const CalendarEventSchema: z.ZodObject<{
    id: z.ZodString;
    source: z.ZodEnum<["google", "outlook", "apple"]>;
    externalID: z.ZodString;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    startDateTime: z.ZodString;
    endDateTime: z.ZodString;
    allDayEvent: z.ZodDefault<z.ZodBoolean>;
    location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    meetingLink: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    color: z.ZodOptional<z.ZodString>;
    organizer: z.ZodOptional<z.ZodString>;
    attendees: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    status: z.ZodDefault<z.ZodEnum<["confirmed", "tentative", "cancelled"]>>;
    recurrenceRule: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isRecurring: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    createdAt: string;
    updatedAt: string;
    status: "cancelled" | "confirmed" | "tentative";
    title: string;
    isRecurring: boolean;
    externalID: string;
    startDateTime: string;
    endDateTime: string;
    allDayEvent: boolean;
    id: string;
    source: "google" | "outlook" | "apple";
    description?: string | null | undefined;
    recurrenceRule?: string | null | undefined;
    location?: string | null | undefined;
    meetingLink?: string | null | undefined;
    color?: string | undefined;
    organizer?: string | undefined;
    attendees?: string[] | undefined;
}, {
    createdAt: string;
    updatedAt: string;
    title: string;
    externalID: string;
    startDateTime: string;
    endDateTime: string;
    id: string;
    source: "google" | "outlook" | "apple";
    status?: "cancelled" | "confirmed" | "tentative" | undefined;
    description?: string | null | undefined;
    isRecurring?: boolean | undefined;
    recurrenceRule?: string | null | undefined;
    allDayEvent?: boolean | undefined;
    location?: string | null | undefined;
    meetingLink?: string | null | undefined;
    color?: string | undefined;
    organizer?: string | undefined;
    attendees?: string[] | undefined;
}>;
export type CalendarEvent = z.infer<typeof CalendarEventSchema>;
//# sourceMappingURL=calendar.schema.d.ts.map