import { z } from 'zod';
export declare const TaskSchema: z.ZodObject<{
    taskID: z.ZodString;
    userID: z.ZodString;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    taskType: z.ZodDefault<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>;
    priorityLevel: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    status: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>;
    completionPercentage: z.ZodDefault<z.ZodNumber>;
    dueDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    dueTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    startDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    startTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    endDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    endTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    locationName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    locationAddress: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    latitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    longitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    estimatedDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    actualDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    timeSpentMinutes: z.ZodDefault<z.ZodNumber>;
    isRecurring: z.ZodDefault<z.ZodBoolean>;
    recurrenceRule: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    parentTaskID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalSource: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
    tags: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    categoryID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isDeleted: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    userID: string;
    isDeleted: boolean;
    createdAt: string;
    updatedAt: string;
    status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
    taskID: string;
    title: string;
    taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
    priorityLevel: "low" | "medium" | "high" | "critical";
    completionPercentage: number;
    timeSpentMinutes: number;
    isRecurring: boolean;
    externalSyncStatus: "not_synced" | "synced" | "failed";
    description?: string | null | undefined;
    dueDate?: string | null | undefined;
    dueTime?: string | null | undefined;
    startDate?: string | null | undefined;
    startTime?: string | null | undefined;
    endDate?: string | null | undefined;
    endTime?: string | null | undefined;
    locationName?: string | null | undefined;
    locationAddress?: string | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    estimatedDurationMinutes?: number | null | undefined;
    actualDurationMinutes?: number | null | undefined;
    recurrenceRule?: string | null | undefined;
    parentTaskID?: string | null | undefined;
    externalID?: string | null | undefined;
    externalSource?: string | null | undefined;
    tags?: string | null | undefined;
    notes?: string | null | undefined;
    categoryID?: string | null | undefined;
}, {
    userID: string;
    createdAt: string;
    updatedAt: string;
    taskID: string;
    title: string;
    isDeleted?: boolean | undefined;
    status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
    description?: string | null | undefined;
    taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
    priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
    completionPercentage?: number | undefined;
    dueDate?: string | null | undefined;
    dueTime?: string | null | undefined;
    startDate?: string | null | undefined;
    startTime?: string | null | undefined;
    endDate?: string | null | undefined;
    endTime?: string | null | undefined;
    locationName?: string | null | undefined;
    locationAddress?: string | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    estimatedDurationMinutes?: number | null | undefined;
    actualDurationMinutes?: number | null | undefined;
    timeSpentMinutes?: number | undefined;
    isRecurring?: boolean | undefined;
    recurrenceRule?: string | null | undefined;
    parentTaskID?: string | null | undefined;
    externalID?: string | null | undefined;
    externalSource?: string | null | undefined;
    externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
    tags?: string | null | undefined;
    notes?: string | null | undefined;
    categoryID?: string | null | undefined;
}>;
export type Task = z.infer<typeof TaskSchema>;
//# sourceMappingURL=tasks.schema.d.ts.map