"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TaskSchema = void 0;
const zod_1 = require("zod");
exports.TaskSchema = zod_1.z.object({
    taskID: zod_1.z.string().uuid(),
    userID: zod_1.z.string().uuid(),
    title: zod_1.z.string().min(1).max(255),
    description: zod_1.z.string().max(4000).optional().nullable(),
    taskType: zod_1.z.enum(['general', 'meeting', 'reminder', 'deadline', 'event']).default('general'),
    priorityLevel: zod_1.z.enum(['low', 'medium', 'high', 'critical']).default('medium'),
    status: zod_1.z.enum(['pending', 'in_progress', 'completed', 'cancelled', 'deferred']).default('pending'),
    completionPercentage: zod_1.z.number().int().min(0).max(100).default(0),
    dueDate: zod_1.z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
    dueTime: zod_1.z.string().regex(/^\d{2}:\d{2}:\d{2}$/).optional().nullable(),
    startDate: zod_1.z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
    startTime: zod_1.z.string().regex(/^\d{2}:\d{2}:\d{2}$/).optional().nullable(),
    endDate: zod_1.z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
    endTime: zod_1.z.string().regex(/^\d{2}:\d{2}:\d{2}$/).optional().nullable(),
    locationName: zod_1.z.string().max(255).optional().nullable(),
    locationAddress: zod_1.z.string().max(500).optional().nullable(),
    latitude: zod_1.z.number().optional().nullable(),
    longitude: zod_1.z.number().optional().nullable(),
    estimatedDurationMinutes: zod_1.z.number().int().positive().optional().nullable(),
    actualDurationMinutes: zod_1.z.number().int().positive().optional().nullable(),
    timeSpentMinutes: zod_1.z.number().int().min(0).default(0),
    isRecurring: zod_1.z.boolean().default(false),
    recurrenceRule: zod_1.z.string().max(500).optional().nullable(),
    parentTaskID: zod_1.z.string().uuid().optional().nullable(),
    externalID: zod_1.z.string().max(255).optional().nullable(),
    externalSource: zod_1.z.string().max(50).optional().nullable(),
    externalSyncStatus: zod_1.z.enum(['not_synced', 'synced', 'failed']).default('not_synced'),
    tags: zod_1.z.string().max(500).optional().nullable(),
    notes: zod_1.z.string().max(2000).optional().nullable(),
    categoryID: zod_1.z.string().uuid().optional().nullable(),
    isDeleted: zod_1.z.boolean().default(false),
    createdAt: zod_1.z.string().datetime({ offset: true }),
    updatedAt: zod_1.z.string().datetime({ offset: true }),
});
//# sourceMappingURL=tasks.schema.js.map