import { z } from 'zod';

export const TaskSchema = z.object({
  taskID: z.string().uuid(),
  userID: z.string().uuid(),
  title: z.string().min(1).max(255),
  description: z.string().max(4000).optional().nullable(),
  taskType: z.enum(['general', 'meeting', 'reminder', 'deadline', 'event']).default('general'),
  priorityLevel: z.enum(['low', 'medium', 'high', 'critical']).default('medium'),
  status: z.enum(['pending', 'in_progress', 'completed', 'cancelled', 'deferred']).default('pending'),
  completionPercentage: z.number().int().min(0).max(100).default(0),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  dueTime: z.string().regex(/^\d{2}:\d{2}:\d{2}$/).optional().nullable(),
  startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  startTime: z.string().regex(/^\d{2}:\d{2}:\d{2}$/).optional().nullable(),
  endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  endTime: z.string().regex(/^\d{2}:\d{2}:\d{2}$/).optional().nullable(),
  locationName: z.string().max(255).optional().nullable(),
  locationAddress: z.string().max(500).optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  estimatedDurationMinutes: z.number().int().positive().optional().nullable(),
  actualDurationMinutes: z.number().int().positive().optional().nullable(),
  timeSpentMinutes: z.number().int().min(0).default(0),
  isRecurring: z.boolean().default(false),
  recurrenceRule: z.string().max(500).optional().nullable(),
  parentTaskID: z.string().uuid().optional().nullable(),
  externalID: z.string().max(255).optional().nullable(),
  externalSource: z.string().max(50).optional().nullable(),
  externalSyncStatus: z.enum(['not_synced', 'synced', 'failed']).default('not_synced'),
  tags: z.string().max(500).optional().nullable(),
  notes: z.string().max(2000).optional().nullable(),
  categoryID: z.string().uuid().optional().nullable(),
  isDeleted: z.boolean().default(false),
  createdAt: z.string().datetime({ offset: true }),
  updatedAt: z.string().datetime({ offset: true }),
});

export type Task = z.infer<typeof TaskSchema>;