import { z } from 'zod';
export declare const GetAppointmentsRequestSchema: z.ZodObject<{
    filters: z.ZodOptional<z.ZodObject<{
        status: z.ZodOptional<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>;
        appointmentType: z.ZodOptional<z.ZodEnum<["general", "doctor", "business", "personal"]>>;
        startDateFrom: z.ZodOptional<z.ZodString>;
        startDateTo: z.ZodOptional<z.ZodString>;
        search: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        search?: string | undefined;
        startDateFrom?: string | undefined;
        startDateTo?: string | undefined;
    }, {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        search?: string | undefined;
        startDateFrom?: string | undefined;
        startDateTo?: string | undefined;
    }>>;
    pagination: z.ZodOptional<z.ZodObject<{
        limit: z.ZodDefault<z.ZodNumber>;
        offset: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        offset: number;
        limit: number;
    }, {
        offset?: number | undefined;
        limit?: number | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    filters?: {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        search?: string | undefined;
        startDateFrom?: string | undefined;
        startDateTo?: string | undefined;
    } | undefined;
    pagination?: {
        offset: number;
        limit: number;
    } | undefined;
}, {
    filters?: {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        search?: string | undefined;
        startDateFrom?: string | undefined;
        startDateTo?: string | undefined;
    } | undefined;
    pagination?: {
        offset?: number | undefined;
        limit?: number | undefined;
    } | undefined;
}>;
export declare const GetAppointmentsResponseSchema: z.ZodObject<{
    appointments: z.ZodArray<z.ZodObject<{
        appointmentID: z.ZodString;
        userID: z.ZodString;
        title: z.ZodString;
        description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        appointmentType: z.ZodDefault<z.ZodEnum<["general", "doctor", "business", "personal"]>>;
        startDateTime: z.ZodString;
        endDateTime: z.ZodString;
        allDayEvent: z.ZodDefault<z.ZodBoolean>;
        location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isVirtual: z.ZodDefault<z.ZodBoolean>;
        meetingLink: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        meetingPlatform: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        status: z.ZodDefault<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>;
        reminderMinutesBefore: z.ZodDefault<z.ZodNumber>;
        isRecurring: z.ZodDefault<z.ZodBoolean>;
        recurrencePattern: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        calendarColor: z.ZodDefault<z.ZodString>;
        externalEventID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
        notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isDeleted: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
        title: string;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        appointmentID: string;
        appointmentType: "general" | "doctor" | "business" | "personal";
        startDateTime: string;
        endDateTime: string;
        allDayEvent: boolean;
        isVirtual: boolean;
        reminderMinutesBefore: number;
        calendarColor: string;
        description?: string | null | undefined;
        notes?: string | null | undefined;
        location?: string | null | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        recurrencePattern?: string | null | undefined;
        externalEventID?: string | null | undefined;
    }, {
        userID: string;
        createdAt: string;
        updatedAt: string;
        title: string;
        appointmentID: string;
        startDateTime: string;
        endDateTime: string;
        isDeleted?: boolean | undefined;
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    }>, "many">;
    total: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    appointments: {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
        title: string;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        appointmentID: string;
        appointmentType: "general" | "doctor" | "business" | "personal";
        startDateTime: string;
        endDateTime: string;
        allDayEvent: boolean;
        isVirtual: boolean;
        reminderMinutesBefore: number;
        calendarColor: string;
        description?: string | null | undefined;
        notes?: string | null | undefined;
        location?: string | null | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        recurrencePattern?: string | null | undefined;
        externalEventID?: string | null | undefined;
    }[];
}, {
    total: number;
    appointments: {
        userID: string;
        createdAt: string;
        updatedAt: string;
        title: string;
        appointmentID: string;
        startDateTime: string;
        endDateTime: string;
        isDeleted?: boolean | undefined;
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    }[];
}>;
export declare const CreateAppointmentRequestSchema: z.ZodObject<Omit<{
    appointmentID: z.ZodString;
    userID: z.ZodString;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    appointmentType: z.ZodDefault<z.ZodEnum<["general", "doctor", "business", "personal"]>>;
    startDateTime: z.ZodString;
    endDateTime: z.ZodString;
    allDayEvent: z.ZodDefault<z.ZodBoolean>;
    location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isVirtual: z.ZodDefault<z.ZodBoolean>;
    meetingLink: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    meetingPlatform: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    status: z.ZodDefault<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>;
    reminderMinutesBefore: z.ZodDefault<z.ZodNumber>;
    isRecurring: z.ZodDefault<z.ZodBoolean>;
    recurrencePattern: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    calendarColor: z.ZodDefault<z.ZodString>;
    externalEventID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isDeleted: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "userID" | "isDeleted" | "createdAt" | "updatedAt" | "appointmentID">, "strip", z.ZodTypeAny, {
    status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
    title: string;
    isRecurring: boolean;
    externalSyncStatus: "not_synced" | "synced" | "failed";
    appointmentType: "general" | "doctor" | "business" | "personal";
    startDateTime: string;
    endDateTime: string;
    allDayEvent: boolean;
    isVirtual: boolean;
    reminderMinutesBefore: number;
    calendarColor: string;
    description?: string | null | undefined;
    notes?: string | null | undefined;
    location?: string | null | undefined;
    meetingLink?: string | null | undefined;
    meetingPlatform?: string | null | undefined;
    recurrencePattern?: string | null | undefined;
    externalEventID?: string | null | undefined;
}, {
    title: string;
    startDateTime: string;
    endDateTime: string;
    status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
    description?: string | null | undefined;
    isRecurring?: boolean | undefined;
    externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
    notes?: string | null | undefined;
    appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
    allDayEvent?: boolean | undefined;
    location?: string | null | undefined;
    isVirtual?: boolean | undefined;
    meetingLink?: string | null | undefined;
    meetingPlatform?: string | null | undefined;
    reminderMinutesBefore?: number | undefined;
    recurrencePattern?: string | null | undefined;
    calendarColor?: string | undefined;
    externalEventID?: string | null | undefined;
}>;
export declare const UpdateAppointmentRequestSchema: z.ZodObject<{
    appointmentID: z.ZodString;
    updates: z.ZodObject<{
        status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>>;
        title: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        isRecurring: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        externalSyncStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>>;
        notes: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        appointmentType: z.ZodOptional<z.ZodDefault<z.ZodEnum<["general", "doctor", "business", "personal"]>>>;
        startDateTime: z.ZodOptional<z.ZodString>;
        endDateTime: z.ZodOptional<z.ZodString>;
        allDayEvent: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        location: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        isVirtual: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        meetingLink: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        meetingPlatform: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        reminderMinutesBefore: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        recurrencePattern: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        calendarColor: z.ZodOptional<z.ZodDefault<z.ZodString>>;
        externalEventID: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    }, "strip", z.ZodTypeAny, {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        startDateTime?: string | undefined;
        endDateTime?: string | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    }, {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        startDateTime?: string | undefined;
        endDateTime?: string | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    appointmentID: string;
    updates: {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        startDateTime?: string | undefined;
        endDateTime?: string | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    };
}, {
    appointmentID: string;
    updates: {
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        startDateTime?: string | undefined;
        endDateTime?: string | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    };
}>;
export declare const DeleteAppointmentRequestSchema: z.ZodObject<{
    appointmentID: z.ZodString;
}, "strip", z.ZodTypeAny, {
    appointmentID: string;
}, {
    appointmentID: string;
}>;
export declare const AppointmentConflictResponseSchema: z.ZodObject<{
    status: z.ZodLiteral<"conflict">;
    serverEntity: z.ZodObject<{
        appointmentID: z.ZodString;
        userID: z.ZodString;
        title: z.ZodString;
        description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        appointmentType: z.ZodDefault<z.ZodEnum<["general", "doctor", "business", "personal"]>>;
        startDateTime: z.ZodString;
        endDateTime: z.ZodString;
        allDayEvent: z.ZodDefault<z.ZodBoolean>;
        location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isVirtual: z.ZodDefault<z.ZodBoolean>;
        meetingLink: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        meetingPlatform: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        status: z.ZodDefault<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>;
        reminderMinutesBefore: z.ZodDefault<z.ZodNumber>;
        isRecurring: z.ZodDefault<z.ZodBoolean>;
        recurrencePattern: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        calendarColor: z.ZodDefault<z.ZodString>;
        externalEventID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
        notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isDeleted: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
        title: string;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        appointmentID: string;
        appointmentType: "general" | "doctor" | "business" | "personal";
        startDateTime: string;
        endDateTime: string;
        allDayEvent: boolean;
        isVirtual: boolean;
        reminderMinutesBefore: number;
        calendarColor: string;
        description?: string | null | undefined;
        notes?: string | null | undefined;
        location?: string | null | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        recurrencePattern?: string | null | undefined;
        externalEventID?: string | null | undefined;
    }, {
        userID: string;
        createdAt: string;
        updatedAt: string;
        title: string;
        appointmentID: string;
        startDateTime: string;
        endDateTime: string;
        isDeleted?: boolean | undefined;
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    }>;
    clientEntity: z.ZodObject<{
        appointmentID: z.ZodString;
        userID: z.ZodString;
        title: z.ZodString;
        description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        appointmentType: z.ZodDefault<z.ZodEnum<["general", "doctor", "business", "personal"]>>;
        startDateTime: z.ZodString;
        endDateTime: z.ZodString;
        allDayEvent: z.ZodDefault<z.ZodBoolean>;
        location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isVirtual: z.ZodDefault<z.ZodBoolean>;
        meetingLink: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        meetingPlatform: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        status: z.ZodDefault<z.ZodEnum<["scheduled", "confirmed", "cancelled", "completed", "rescheduled"]>>;
        reminderMinutesBefore: z.ZodDefault<z.ZodNumber>;
        isRecurring: z.ZodDefault<z.ZodBoolean>;
        recurrencePattern: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        calendarColor: z.ZodDefault<z.ZodString>;
        externalEventID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
        notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isDeleted: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
        title: string;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        appointmentID: string;
        appointmentType: "general" | "doctor" | "business" | "personal";
        startDateTime: string;
        endDateTime: string;
        allDayEvent: boolean;
        isVirtual: boolean;
        reminderMinutesBefore: number;
        calendarColor: string;
        description?: string | null | undefined;
        notes?: string | null | undefined;
        location?: string | null | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        recurrencePattern?: string | null | undefined;
        externalEventID?: string | null | undefined;
    }, {
        userID: string;
        createdAt: string;
        updatedAt: string;
        title: string;
        appointmentID: string;
        startDateTime: string;
        endDateTime: string;
        isDeleted?: boolean | undefined;
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    status: "conflict";
    serverEntity: {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
        title: string;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        appointmentID: string;
        appointmentType: "general" | "doctor" | "business" | "personal";
        startDateTime: string;
        endDateTime: string;
        allDayEvent: boolean;
        isVirtual: boolean;
        reminderMinutesBefore: number;
        calendarColor: string;
        description?: string | null | undefined;
        notes?: string | null | undefined;
        location?: string | null | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        recurrencePattern?: string | null | undefined;
        externalEventID?: string | null | undefined;
    };
    clientEntity: {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled";
        title: string;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        appointmentID: string;
        appointmentType: "general" | "doctor" | "business" | "personal";
        startDateTime: string;
        endDateTime: string;
        allDayEvent: boolean;
        isVirtual: boolean;
        reminderMinutesBefore: number;
        calendarColor: string;
        description?: string | null | undefined;
        notes?: string | null | undefined;
        location?: string | null | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        recurrencePattern?: string | null | undefined;
        externalEventID?: string | null | undefined;
    };
}, {
    status: "conflict";
    serverEntity: {
        userID: string;
        createdAt: string;
        updatedAt: string;
        title: string;
        appointmentID: string;
        startDateTime: string;
        endDateTime: string;
        isDeleted?: boolean | undefined;
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    };
    clientEntity: {
        userID: string;
        createdAt: string;
        updatedAt: string;
        title: string;
        appointmentID: string;
        startDateTime: string;
        endDateTime: string;
        isDeleted?: boolean | undefined;
        status?: "completed" | "cancelled" | "scheduled" | "confirmed" | "rescheduled" | undefined;
        description?: string | null | undefined;
        isRecurring?: boolean | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        notes?: string | null | undefined;
        appointmentType?: "general" | "doctor" | "business" | "personal" | undefined;
        allDayEvent?: boolean | undefined;
        location?: string | null | undefined;
        isVirtual?: boolean | undefined;
        meetingLink?: string | null | undefined;
        meetingPlatform?: string | null | undefined;
        reminderMinutesBefore?: number | undefined;
        recurrencePattern?: string | null | undefined;
        calendarColor?: string | undefined;
        externalEventID?: string | null | undefined;
    };
}>;
export type GetAppointmentsRequest = z.infer<typeof GetAppointmentsRequestSchema>;
export type GetAppointmentsResponse = z.infer<typeof GetAppointmentsResponseSchema>;
export type CreateAppointmentRequest = z.infer<typeof CreateAppointmentRequestSchema>;
export type UpdateAppointmentRequest = z.infer<typeof UpdateAppointmentRequestSchema>;
export type DeleteAppointmentRequest = z.infer<typeof DeleteAppointmentRequestSchema>;
export type AppointmentConflictResponse = z.infer<typeof AppointmentConflictResponseSchema>;
//# sourceMappingURL=appointments.contract.d.ts.map