import { z } from 'zod';
export declare const GetTasksRequestSchema: z.ZodObject<{
    filters: z.ZodOptional<z.ZodObject<{
        status: z.ZodOptional<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>;
        priority: z.ZodOptional<z.ZodEnum<["low", "medium", "high", "critical"]>>;
        taskType: z.ZodOptional<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>;
        dueDateFrom: z.ZodOptional<z.ZodString>;
        dueDateTo: z.ZodOptional<z.ZodString>;
        search: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priority?: "low" | "medium" | "high" | "critical" | undefined;
        dueDateFrom?: string | undefined;
        dueDateTo?: string | undefined;
        search?: string | undefined;
    }, {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priority?: "low" | "medium" | "high" | "critical" | undefined;
        dueDateFrom?: string | undefined;
        dueDateTo?: string | undefined;
        search?: string | undefined;
    }>>;
    pagination: z.ZodOptional<z.ZodObject<{
        limit: z.ZodDefault<z.ZodNumber>;
        offset: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        offset: number;
        limit: number;
    }, {
        offset?: number | undefined;
        limit?: number | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    filters?: {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priority?: "low" | "medium" | "high" | "critical" | undefined;
        dueDateFrom?: string | undefined;
        dueDateTo?: string | undefined;
        search?: string | undefined;
    } | undefined;
    pagination?: {
        offset: number;
        limit: number;
    } | undefined;
}, {
    filters?: {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priority?: "low" | "medium" | "high" | "critical" | undefined;
        dueDateFrom?: string | undefined;
        dueDateTo?: string | undefined;
        search?: string | undefined;
    } | undefined;
    pagination?: {
        offset?: number | undefined;
        limit?: number | undefined;
    } | undefined;
}>;
export declare const GetTasksResponseSchema: z.ZodObject<{
    tasks: z.ZodArray<z.ZodObject<{
        taskID: z.ZodString;
        userID: z.ZodString;
        title: z.ZodString;
        description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        taskType: z.ZodDefault<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>;
        priorityLevel: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
        status: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>;
        completionPercentage: z.ZodDefault<z.ZodNumber>;
        dueDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        dueTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        startDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        startTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        endDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        endTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        locationName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        locationAddress: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        latitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        longitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        estimatedDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        actualDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        timeSpentMinutes: z.ZodDefault<z.ZodNumber>;
        isRecurring: z.ZodDefault<z.ZodBoolean>;
        recurrenceRule: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        parentTaskID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSource: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
        tags: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        categoryID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isDeleted: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
        taskID: string;
        title: string;
        taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
        priorityLevel: "low" | "medium" | "high" | "critical";
        completionPercentage: number;
        timeSpentMinutes: number;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        description?: string | null | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }, {
        userID: string;
        createdAt: string;
        updatedAt: string;
        taskID: string;
        title: string;
        isDeleted?: boolean | undefined;
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }>, "many">;
    total: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    tasks: {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
        taskID: string;
        title: string;
        taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
        priorityLevel: "low" | "medium" | "high" | "critical";
        completionPercentage: number;
        timeSpentMinutes: number;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        description?: string | null | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }[];
    total: number;
}, {
    tasks: {
        userID: string;
        createdAt: string;
        updatedAt: string;
        taskID: string;
        title: string;
        isDeleted?: boolean | undefined;
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }[];
    total: number;
}>;
export declare const CreateTaskRequestSchema: z.ZodObject<Omit<{
    taskID: z.ZodString;
    userID: z.ZodString;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    taskType: z.ZodDefault<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>;
    priorityLevel: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    status: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>;
    completionPercentage: z.ZodDefault<z.ZodNumber>;
    dueDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    dueTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    startDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    startTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    endDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    endTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    locationName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    locationAddress: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    latitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    longitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    estimatedDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    actualDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    timeSpentMinutes: z.ZodDefault<z.ZodNumber>;
    isRecurring: z.ZodDefault<z.ZodBoolean>;
    recurrenceRule: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    parentTaskID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalSource: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
    tags: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    categoryID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isDeleted: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "userID" | "isDeleted" | "createdAt" | "updatedAt" | "taskID">, "strip", z.ZodTypeAny, {
    status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
    title: string;
    taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
    priorityLevel: "low" | "medium" | "high" | "critical";
    completionPercentage: number;
    timeSpentMinutes: number;
    isRecurring: boolean;
    externalSyncStatus: "not_synced" | "synced" | "failed";
    description?: string | null | undefined;
    dueDate?: string | null | undefined;
    dueTime?: string | null | undefined;
    startDate?: string | null | undefined;
    startTime?: string | null | undefined;
    endDate?: string | null | undefined;
    endTime?: string | null | undefined;
    locationName?: string | null | undefined;
    locationAddress?: string | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    estimatedDurationMinutes?: number | null | undefined;
    actualDurationMinutes?: number | null | undefined;
    recurrenceRule?: string | null | undefined;
    parentTaskID?: string | null | undefined;
    externalID?: string | null | undefined;
    externalSource?: string | null | undefined;
    tags?: string | null | undefined;
    notes?: string | null | undefined;
    categoryID?: string | null | undefined;
}, {
    title: string;
    status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
    description?: string | null | undefined;
    taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
    priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
    completionPercentage?: number | undefined;
    dueDate?: string | null | undefined;
    dueTime?: string | null | undefined;
    startDate?: string | null | undefined;
    startTime?: string | null | undefined;
    endDate?: string | null | undefined;
    endTime?: string | null | undefined;
    locationName?: string | null | undefined;
    locationAddress?: string | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    estimatedDurationMinutes?: number | null | undefined;
    actualDurationMinutes?: number | null | undefined;
    timeSpentMinutes?: number | undefined;
    isRecurring?: boolean | undefined;
    recurrenceRule?: string | null | undefined;
    parentTaskID?: string | null | undefined;
    externalID?: string | null | undefined;
    externalSource?: string | null | undefined;
    externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
    tags?: string | null | undefined;
    notes?: string | null | undefined;
    categoryID?: string | null | undefined;
}>;
export declare const UpdateTaskRequestSchema: z.ZodObject<{
    taskID: z.ZodString;
    updates: z.ZodObject<{
        status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>>;
        title: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        taskType: z.ZodOptional<z.ZodDefault<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>>;
        priorityLevel: z.ZodOptional<z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>>;
        completionPercentage: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        dueDate: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        dueTime: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        startDate: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        startTime: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        endDate: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        endTime: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        locationName: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        locationAddress: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        latitude: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
        longitude: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
        estimatedDurationMinutes: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
        actualDurationMinutes: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
        timeSpentMinutes: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        isRecurring: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        recurrenceRule: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        parentTaskID: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        externalID: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        externalSource: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        externalSyncStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>>;
        tags: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        notes: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
        categoryID: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    }, "strip", z.ZodTypeAny, {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }, {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    taskID: string;
    updates: {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    };
}, {
    taskID: string;
    updates: {
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        title?: string | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    };
}>;
export declare const DeleteTaskRequestSchema: z.ZodObject<{
    taskID: z.ZodString;
}, "strip", z.ZodTypeAny, {
    taskID: string;
}, {
    taskID: string;
}>;
export declare const CompleteTaskRequestSchema: z.ZodObject<{
    taskID: z.ZodString;
    completionPercentage: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    taskID: string;
    completionPercentage: number;
}, {
    taskID: string;
    completionPercentage: number;
}>;
export declare const TaskConflictResponseSchema: z.ZodObject<{
    status: z.ZodLiteral<"conflict">;
    serverEntity: z.ZodObject<{
        taskID: z.ZodString;
        userID: z.ZodString;
        title: z.ZodString;
        description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        taskType: z.ZodDefault<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>;
        priorityLevel: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
        status: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>;
        completionPercentage: z.ZodDefault<z.ZodNumber>;
        dueDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        dueTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        startDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        startTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        endDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        endTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        locationName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        locationAddress: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        latitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        longitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        estimatedDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        actualDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        timeSpentMinutes: z.ZodDefault<z.ZodNumber>;
        isRecurring: z.ZodDefault<z.ZodBoolean>;
        recurrenceRule: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        parentTaskID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSource: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
        tags: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        categoryID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isDeleted: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
        taskID: string;
        title: string;
        taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
        priorityLevel: "low" | "medium" | "high" | "critical";
        completionPercentage: number;
        timeSpentMinutes: number;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        description?: string | null | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }, {
        userID: string;
        createdAt: string;
        updatedAt: string;
        taskID: string;
        title: string;
        isDeleted?: boolean | undefined;
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }>;
    clientEntity: z.ZodObject<{
        taskID: z.ZodString;
        userID: z.ZodString;
        title: z.ZodString;
        description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        taskType: z.ZodDefault<z.ZodEnum<["general", "meeting", "reminder", "deadline", "event"]>>;
        priorityLevel: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
        status: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "cancelled", "deferred"]>>;
        completionPercentage: z.ZodDefault<z.ZodNumber>;
        dueDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        dueTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        startDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        startTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        endDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        endTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        locationName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        locationAddress: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        latitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        longitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        estimatedDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        actualDurationMinutes: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        timeSpentMinutes: z.ZodDefault<z.ZodNumber>;
        isRecurring: z.ZodDefault<z.ZodBoolean>;
        recurrenceRule: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        parentTaskID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSource: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        externalSyncStatus: z.ZodDefault<z.ZodEnum<["not_synced", "synced", "failed"]>>;
        tags: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        categoryID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        isDeleted: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
        taskID: string;
        title: string;
        taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
        priorityLevel: "low" | "medium" | "high" | "critical";
        completionPercentage: number;
        timeSpentMinutes: number;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        description?: string | null | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }, {
        userID: string;
        createdAt: string;
        updatedAt: string;
        taskID: string;
        title: string;
        isDeleted?: boolean | undefined;
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    status: "conflict";
    serverEntity: {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
        taskID: string;
        title: string;
        taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
        priorityLevel: "low" | "medium" | "high" | "critical";
        completionPercentage: number;
        timeSpentMinutes: number;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        description?: string | null | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    };
    clientEntity: {
        userID: string;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
        status: "pending" | "in_progress" | "completed" | "cancelled" | "deferred";
        taskID: string;
        title: string;
        taskType: "general" | "meeting" | "reminder" | "deadline" | "event";
        priorityLevel: "low" | "medium" | "high" | "critical";
        completionPercentage: number;
        timeSpentMinutes: number;
        isRecurring: boolean;
        externalSyncStatus: "not_synced" | "synced" | "failed";
        description?: string | null | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    };
}, {
    status: "conflict";
    serverEntity: {
        userID: string;
        createdAt: string;
        updatedAt: string;
        taskID: string;
        title: string;
        isDeleted?: boolean | undefined;
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    };
    clientEntity: {
        userID: string;
        createdAt: string;
        updatedAt: string;
        taskID: string;
        title: string;
        isDeleted?: boolean | undefined;
        status?: "pending" | "in_progress" | "completed" | "cancelled" | "deferred" | undefined;
        description?: string | null | undefined;
        taskType?: "general" | "meeting" | "reminder" | "deadline" | "event" | undefined;
        priorityLevel?: "low" | "medium" | "high" | "critical" | undefined;
        completionPercentage?: number | undefined;
        dueDate?: string | null | undefined;
        dueTime?: string | null | undefined;
        startDate?: string | null | undefined;
        startTime?: string | null | undefined;
        endDate?: string | null | undefined;
        endTime?: string | null | undefined;
        locationName?: string | null | undefined;
        locationAddress?: string | null | undefined;
        latitude?: number | null | undefined;
        longitude?: number | null | undefined;
        estimatedDurationMinutes?: number | null | undefined;
        actualDurationMinutes?: number | null | undefined;
        timeSpentMinutes?: number | undefined;
        isRecurring?: boolean | undefined;
        recurrenceRule?: string | null | undefined;
        parentTaskID?: string | null | undefined;
        externalID?: string | null | undefined;
        externalSource?: string | null | undefined;
        externalSyncStatus?: "not_synced" | "synced" | "failed" | undefined;
        tags?: string | null | undefined;
        notes?: string | null | undefined;
        categoryID?: string | null | undefined;
    };
}>;
export type GetTasksRequest = z.infer<typeof GetTasksRequestSchema>;
export type GetTasksResponse = z.infer<typeof GetTasksResponseSchema>;
export type CreateTaskRequest = z.infer<typeof CreateTaskRequestSchema>;
export type UpdateTaskRequest = z.infer<typeof UpdateTaskRequestSchema>;
export type DeleteTaskRequest = z.infer<typeof DeleteTaskRequestSchema>;
export type CompleteTaskRequest = z.infer<typeof CompleteTaskRequestSchema>;
export type TaskConflictResponse = z.infer<typeof TaskConflictResponseSchema>;
//# sourceMappingURL=tasks.contract.d.ts.map