export declare const IPC_CHANNELS: {
    readonly AUTH_LOGIN: "ipc:auth:login";
    readonly AUTH_LOGOUT: "ipc:auth:logout";
    readonly AUTH_VALIDATE: "ipc:auth:validate";
    readonly TASKS_GET: "ipc:tasks:get";
    readonly TASKS_CREATE: "ipc:tasks:create";
    readonly TASKS_UPDATE: "ipc:tasks:update";
    readonly TASKS_DELETE: "ipc:tasks:delete";
    readonly TASKS_COMPLETE: "ipc:tasks:complete";
    readonly APPOINTMENTS_GET: "ipc:appointments:get";
    readonly APPOINTMENTS_CREATE: "ipc:appointments:create";
    readonly APPOINTMENTS_UPDATE: "ipc:appointments:update";
    readonly APPOINTMENTS_DELETE: "ipc:appointments:delete";
    readonly EVENTS_GET: "ipc:events:get";
    readonly EVENTS_CREATE: "ipc:events:create";
    readonly EVENTS_UPDATE: "ipc:events:update";
    readonly EVENTS_DELETE: "ipc:events:delete";
    readonly MEETINGS_GET: "ipc:meetings:get";
    readonly MEETINGS_CREATE: "ipc:meetings:create";
    readonly MEETINGS_UPDATE: "ipc:meetings:update";
    readonly MEETINGS_DELETE: "ipc:meetings:delete";
    readonly NOTES_GET: "ipc:notes:get";
    readonly NOTES_CREATE: "ipc:notes:create";
    readonly NOTES_UPDATE: "ipc:notes:update";
    readonly NOTES_DELETE: "ipc:notes:delete";
    readonly CALENDAR_SYNC: "ipc:calendar:sync";
    readonly CALENDAR_GET_EVENTS: "ipc:calendar:getEvents";
    readonly CHAT_SEND: "ipc:chat:send";
    readonly CHAT_GET_MESSAGES: "ipc:chat:getMessages";
    readonly CHAT_OBSERVE: "ipc:chat:observe";
    readonly ANALYTICS_GENERATE: "ipc:analytics:generate";
    readonly ANALYTICS_GET_SCORE: "ipc:analytics:getScore";
    readonly SETTINGS_GET: "ipc:settings:get";
    readonly SETTINGS_UPDATE: "ipc:settings:update";
    readonly SYNC_PUSH: "ipc:sync:push";
    readonly SYNC_PULL: "ipc:sync:pull";
};
//# sourceMappingURL=channels.d.ts.map